{{- if eq .Values.priorityClasses.create false }}
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ .Values.priorityClasses.critical }}
value: 1000000
globalDefault: false
description: "This priority class will be used to ensure opslevel mysql pod preempts other self-hosted workloads."
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ .Values.priorityClasses.high }}
value: 10000
globalDefault: false
description: "This priority class will be used for statefulsets to ensure they preempts other self-hosted workloads."
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ .Values.priorityClasses.normal }}
value: 100
globalDefault: false
description: "This priority class will be used for all other self-hosted workloads."
{{- end }}
