{{ if (.Values.global.dockerconfigjson | default (.Values.global.replicated).dockerconfigjson | default false ) }}
apiVersion: v1
kind: Secret
metadata:
  name: opslevel-pull-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: '{{ (.Values.global.dockerconfigjson | default (.Values.global.replicated).dockerconfigjson ) }}'
{{ end }}