# https://taskfile.dev
version: '3'

vars:
  VERSION_DYNAMIC:
    sh: cat ./charts/opslevel/Chart.yaml | yq '.version'

tasks:
  setup:
    desc: Setup and Install all tools and dependencies needed for these tasks
    cmds:
      - task: install-brew
      - task: install-kubectl
      - task: install-helm
      - task: install-krew
      - task: install-kubectl-slice
      - task: install-replicated

  lint:
    desc: Check formatting and linting
    cmds:
      - task: setup
      - task: lint-self-hosted

  internal-release:
    desc: Workflow that releases the self-hosted helm chart for internal use
    deps:
      - setup
    cmds:
      - task: package-self-hosted
      - task: lint-self-hosted
      - task: publish-self-hosted
        vars: { REPLICATED_CHANNEL: 'Helm-Unstable' }

  public-release:
    desc: Workflow that releases the self-hosted helm chart to customers
    deps:
      - setup
    cmds:
      - task: package-self-hosted
      - task: lint-self-hosted
      - task: publish-self-hosted
        vars: { REPLICATED_CHANNEL: 'Helm' }

  release-self-hosted:
    desc: Workflow that packages, lints and releases the self-hosted helm chart
    deps:
      - setup
    cmds:
      - task: package-self-hosted
      - task: lint-self-hosted
      - task: publish-self-hosted

  render-self-hosted:
    desc: Workflow that runs helm template and kubectl slice to inspected the rendered template
    deps:
      - setup
    cmds:
      - helm template ./charts/opslevel > all.yaml
      - kubectl slice --input-file=all.yaml --output-dir=./rendered
      - rm all.yaml

  pull-self-hosted:
    desc: Pull the replicated helm chart down to disk to inspect it
    deps:
      - setup
    requires:
      vars: [ REPLICATED_CHANNEL ]
    cmds:
      - mkdir -p ./downloads
      - helm pull --untar --untardir=./downloads oci://registry.replicated.com/opslevel/{{ .REPLICATED_CHANNEL | lower }}/opslevel

  # Internal

  lint-self-hosted:
    internal: true
    cmds:
      - replicated release lint --chart ./manifests/opslevel-{{ .VERSION_DYNAMIC }}.tgz --app opslevel

  package-self-hosted:
    internal: true
    cmds:
      - helm package ./charts/opslevel --dependency-update
      - mkdir -p ./manifests
      - mv ./opslevel-{{ .VERSION_DYNAMIC }}.tgz ./manifests/opslevel-{{.VERSION_DYNAMIC}}.tgz

  publish-self-hosted:
    internal: true
    requires:
      vars: [ REPLICATED_CHANNEL ]
    deps:
      - install-replicated
    cmds:
      - replicated release create --chart ./manifests/opslevel-{{ .VERSION_DYNAMIC }}.tgz --app opslevel --version "{{ .VERSION_DYNAMIC }}" --promote "{{ .REPLICATED_CHANNEL }}" -y

  install-brew:
    internal: true
    platforms: [darwin]
    status:
      - which brew
    cmds:
      - /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

  install-kubectl:
    internal: true
    platforms: [darwin]
    status:
      - which kubectl
    cmds:
      - brew install kubectl

  install-helm:
    internal: true
    platforms: [darwin]
    status:
      - which helm
    cmds:
      - brew install helm

  install-krew:
    internal: true
    platforms: [darwin]
    status:
      - which kubectl-krew
    cmds:
      - brew install krew

  install-kubectl-slice:
    internal: true
    platforms: [darwin]
    status:
      - which kubectl-slice
    cmds:
      - kubectl krew install slice

  install-replicated:
    internal: true
    platforms: [darwin]
    status:
      - which replicated
    cmds:
      - brew install replicatedhq/replicated/cli
