{{- if .Values.opslevel.ingress.create }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.opslevel.ingress.name }}
{{- with .Values.opslevel.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.opslevel.ingress.ingressClassName }}
  ingressClassName: {{ .Values.opslevel.ingress.ingressClassName}}
{{- end }}
{{- if .Values.opslevel.ingress.tls }}
  tls:
    - hosts:
        - '{{ .Values.opslevel.subdomain }}.{{ .Values.opslevel.domain }}'
{{- end }}
  rules:
    - host: '{{ .Values.opslevel.subdomain }}.{{ .Values.opslevel.domain }}'
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.opslevel.service.name }}
                port:
                  name: http
{{- end }}