{{- if .Values.opslevel.ingress.create }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.opslevel.ingress.name }}
{{- with .Values.opslevel.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.opslevel.ingress.ingressClassName }}
  ingressClassName: {{ .Values.opslevel.ingress.ingressClassName}}
{{- end }}
{{- with .Values.opslevel.ingress.tls }}
  tls:
{{ toYaml . | indent 6 }}
{{- end }}
{{- with .Values.opslevel.ingress.rules }}
  rules:
{{ toYaml . | indent 6 }}
{{- end }}
{{- end }}