apiVersion: apps/v1
kind: Deployment
metadata:
  name: opslevel-scheduler
  labels:
    app.kubernetes.io/component: scheduler
    app.kubernetes.io/part-of: opslevel
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 75%
  selector:
    matchLabels:
      app.kuberntes.io/component: scheduler
      app.kubernetes.io/part-of: opslevel
  template:
    metadata:
      labels:
        app.kuberntes.io/component: scheduler
        app.kubernetes.io/part-of: opslevel
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/opslevel/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/opslevel/secret.yaml") . | sha256sum }}
    spec:
      {{- template "opslevel.pullSecrets" . }}
      {{- template "global.nodeSelector" . }}
      priorityClassName: opslevel-normal
      terminationGracePeriodSeconds: 300
      initContainers:
        {{- if .Values.global.certificate }}
        - name: init-certs
          image: "{{ template "opslevel.image" . }}"
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - sleep 10; update-ca-certificates; cp -r /etc/ssl/certs/. /data;
          volumeMounts:
            - name: certificate
              mountPath: /usr/local/share/ca-certificates/custom-cert.crt
              subPath: custom-cert.crt
              readOnly: false
            - name: ca
              mountPath: /data
              readOnly: false
        {{- end }}
        - name: migrations
          image: "{{ template "opslevel.image" . }}"
          args:
            - ./bin/init-db
          env: &env
            - name: SIDEKIQ_CONCURRENCY
              value: "1"
            - name: SIDEKIQ_SCHEDULER
              value: "true"
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          envFrom: &envFrom
            - configMapRef:
                name: 'opslevel'
            - secretRef:
                name: 'opslevel'
            - secretRef:
                name: '{{ .Values.redis.secret.name }}'
            - secretRef:
                name: '{{ .Values.elasticsearch.secret.name }}'
            {{- template "opslevel.integration.secrets" . }}
          {{- if .Values.global.certificate }}
          volumeMounts:
            - name: certificate
              mountPath: /usr/local/share/ca-certificates/custom-cert.crt
              subPath: custom-cert.crt
              readOnly: false
            - name: ca
              mountPath: /etc/ssl/certs
          {{- end }}
      containers:
        - name: scheduler
          image: "{{ template "opslevel.image" . }}"
          imagePullPolicy: IfNotPresent
          args:
            - bundle
            - exec
            - sidekiq
          envFrom: *envFrom
          env: *env
          {{- with .Values.opslevel.workerLow.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.global.certificate }}
          volumeMounts:
            - name: certificate
              mountPath: /usr/local/share/ca-certificates/custom-cert.crt
              subPath: custom-cert.crt
              readOnly: false
            - name: ca
              mountPath: /etc/ssl/certs
          {{- end }}
      {{- if .Values.global.certificate }}
      volumes:
        - name: ca
          emptyDir: {}
        - name: certificate
          secret:
            secretName: opslevel-certificate
      {{- end }}
