apiVersion: v1
kind: Secret
metadata:
  name: opslevel
  labels:
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: opslevel
type: Opaque
data:
  # Please Keep Alphabetized
  ACTIVE_STORAGE_{{ .Values.objectStorage.type | upper }}_ACCESS_KEY_ID: '{{ .Values.objectStorage.secret.accessKey | b64enc }}'
  ACTIVE_STORAGE_{{ .Values.objectStorage.type | upper }}_SECRET_ACCESS_KEY: '{{ .Values.objectStorage.secret.secretKey | b64enc }}'
  DATABASE_HOST: '{{ .Values.mysql.secret.host | b64enc }}'
  DATABASE_PORT: '{{ .Values.mysql.secret.port | b64enc }}'
  DATABASE_USERNAME: '{{ .Values.mysql.secret.username | b64enc }}'
  DATABASE_PASSWORD: '{{ .Values.mysql.secret.password | b64enc }}'
  DATABASE_NAME: '{{ .Values.mysql.secret.databaseName | b64enc }}'
  DEV_PASSWORD: '{{ .Values.opslevel.account.password | b64enc }}'
  DEVISE_PEPPER: '{{ .Values.opslevel.secret.devisePepper | b64enc }}'
  DEVISE_SECRET_KEY: '{{ .Values.opslevel.secret.deviseSecretKey | b64enc }}'
  ELASTICSEARCH_ENABLED: 'dHJ1ZQ=='
  ELASTICSEARCH_PROTOCOL: '{{ .Values.elasticsearch.secret.protocol | b64enc }}'
  ELASTICSEARCH_USERNAME: '{{ .Values.elasticsearch.secret.username | b64enc }}'
  ELASTICSEARCH_PASSWORD: '{{ .Values.elasticsearch.secret.password | b64enc }}'
  ELASTICSEARCH_HOSTNAME: '{{ .Values.elasticsearch.secret.host | b64enc }}'
  ELASTICSEARCH_PORT: '{{ .Values.elasticsearch.secret.port | b64enc }}'
  ENCRYPTION_SALT: '{{ .Values.opslevel.secret.encryptionSalt | b64enc }}'
  EXTERNAL_UUID_PEPPER: '{{ .Values.opslevel.secret.externalUUIDPepper | b64enc }}'
  SECRET_KEY_BASE: '{{ .Values.opslevel.secret.secretKeyBase | b64enc }}'
  SMTP_PASSWORD: '{{ .Values.smtp.secret.password | b64enc }}'
  THROTTLER_PEPPER: '{{ .Values.opslevel.secret.throttlerPepper | b64enc }}'

{{- if .Values.integrations.azureDevOps.enabled }}
{{- if .Values.integrations.azureDevOps.secret.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: '{{ .Values.integrations.azureDevOps.secret.name }}'
  labels:
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: opslevel
type: Opaque
data:
  AZURE_DEVOPS_ENABLED: '{{ .Values.integrations.azureDevOps.enabled | toString | b64enc }}'
  AZURE_DEVOPS_APP_ID: '{{ required "please provide 'integrations.azureDevOps.secret.appId'" .Values.integrations.azureDevOps.secret.appId | b64enc }}'
  AZURE_DEVOPS_CLIENT_SECRET: '{{ required "please provide 'integrations.azureDevOps.secret.clientSecret'" .Values.integrations.azureDevOps.secret.clientSecret | b64enc }}'
{{- end }}
{{- end }}

{{- if .Values.integrations.bitbucket.enabled }}
{{- if .Values.integrations.bitbucket.secret.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: '{{ .Values.integrations.bitbucket.secret.name }}'
  labels:
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: opslevel
type: Opaque
data:
  BITBUCKET_ENABLED: '{{ .Values.integrations.bitbucket.enabled | toString | b64enc }}'
  BITBUCKET_WEBHOOK_SECRET: '{{ required "please provide 'integrations.bitbucket.secret.webhookSecret'" .Values.integrations.bitbucket.secret.webhookSecret | b64enc }}'
{{- end }}
{{- end }}

{{- if .Values.integrations.github.enabled }}
{{- if .Values.integrations.github.secret.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: '{{ .Values.integrations.github.secret.name }}'
  labels:
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: opslevel
type: Opaque
data:
  GITHUB_ENABLED: '{{ .Values.integrations.github.enabled | toString | b64enc }}'
  GITHUB_APP_IDENTIFIER: '{{ required "please provide 'integrations.github.secret.appId'" .Values.integrations.github.secret.appId | b64enc }}'
  GITHUB_PRIVATE_KEY: '{{ required "please provide 'integrations.github.secret.privateKey'" .Values.integrations.github.secret.privateKey | b64enc }}'
  GITHUB_WEBHOOK_SECRET: '{{ required "please provide 'integrations.github.secret.webhookSecret'" .Values.integrations.github.secret.webhookSecret | b64enc }}'
  GITHUB_INSTALL_URL: '{{ template "github.install.url" . | b64enc }}'
{{- end }}
{{- end }}

{{- if .Values.integrations.gitlab.enabled }}
{{- if .Values.integrations.gitlab.secret.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: '{{ .Values.integrations.gitlab.secret.name }}'
  labels:
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: opslevel
type: Opaque
data:
  GITLAB_ENABLED: '{{ .Values.integrations.gitlab.enabled | toString | b64enc }}'
  GITLAB_APP_IDENTIFIER: '{{ required "please provide 'integrations.gitlab.secret.appId'" .Values.integrations.gitlab.secret.appId | b64enc }}'
  GITLAB_APP_SECRET: '{{ required "please provide 'integrations.gitlab.secret.appSecret'" .Values.integrations.gitlab.secret.appSecret | b64enc }}'
{{- end }}
{{- end }}

{{- if .Values.integrations.jira.enabled }}
{{- if .Values.integrations.jira.secret.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: '{{ .Values.integrations.jira.secret.name }}'
  labels:
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: opslevel
type: Opaque
data:
  JIRA_ENABLED: '{{ .Values.integrations.jira.enabled | toString | b64enc }}'
  JIRA_SOFTWARE_APP_CLIENT_ID: '{{ required "please provide 'integrations.jira.secret.appClientId'" .Values.integrations.jira.secret.appClientId | b64enc }}'
  JIRA_SOFTWARE_APP_SECRET: '{{ required "please provide 'integrations.jira.secret.appSecret'" .Values.integrations.jira.secret.appSecret | b64enc }}'
{{- end }}
{{- end }}

{{- if .Values.integrations.pagerduty.enabled }}
{{- if .Values.integrations.pagerduty.secret.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: '{{ .Values.integrations.pagerduty.secret.name }}'
  labels:
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: opslevel
type: Opaque
data:
  PAGERDUTY_ENABLED: '{{ .Values.integrations.pagerduty.enabled | toString | b64enc }}'
  PAGERDUTY_APP_CLIENT_ID: '{{ required "please provide 'integrations.pagerduty.secret.usAppClientId'" .Values.integrations.pagerduty.secret.usAppClientId | b64enc }}'
  PAGERDUTY_APP_CLIENT_SECRET: '{{ required "please provide 'integrations.pagerduty.secret.usAppClientSecret'" .Values.integrations.pagerduty.secret.usAppClientSecret | b64enc }}'
{{- end }}
{{- end }}

{{- if .Values.integrations.slack.enabled }}
{{- if .Values.integrations.slack.secret.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: '{{ .Values.integrations.slack.secret.name }}'
  labels:
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: opslevel
type: Opaque
data:
  SLACK_ENABLED: '{{ .Values.integrations.slack.enabled | toString | b64enc }}'
  SLACK_CLIENT_ID: '{{ required "please provide 'integrations.slack.secret.clientId'" .Values.integrations.slack.secret.clientId | b64enc }}'
  SLACK_CLIENT_SECRET: '{{ required "please provide 'integrations.slack.secret.clientSecret'" .Values.integrations.slack.secret.clientSecret | b64enc }}'
  SLACK_SIGNING_SECRET: '{{ required "please provide 'integrations.slack.secret.signingSecret'" .Values.integrations.slack.secret.signingSecret | b64enc }}'
  SLACK_VERIFICATION_TOKEN: '{{ required "please provide 'integrations.slack.secret.verificationToken'" .Values.integrations.slack.secret.verificationToken | b64enc }}'
{{- end }}
{{- end }}
