{{- if .Values.opslevel.service.create }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.opslevel.service.name }}
  labels:
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: opslevel
{{- with .Values.opslevel.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  selector:
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: opslevel
{{- end }}