apiVersion: v1
kind: Service
metadata:
  name: opslevel
  labels:
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: opslevel
spec:
  ports:
  - name: http
    port: 80
    targetPort: 3000
  selector:
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: opslevel

