{{- if .Values.opssight.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: '{{ .Values.opssight.secret.name }}'
  labels:
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: opssight
type: Opaque
data:
  DB_PASSWORD: '{{ .Values.postgres.secret.password | b64enc}}'
  REDIS_PASSWORD: '{{ .Values.redis.secret.password | b64enc }}'
  SECRET_KEY_BASE: '{{ .Values.opssight.secret.secretKeyBase | b64enc}}'
{{- end }}