{{- if .Values.opssight.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: opssight
  labels:
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: opssight
spec:
  ports:
  - name: http
    port: 80
    targetPort: 3000
  selector:
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: opssight
{{- end }}