{{- if .Values.opssight.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opssight-worker
  labels:
    app.kubernetes.io/component: worker
    app.kubernetes.io/part-of: opssight
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/component: worker
      app.kubernetes.io/part-of: opssight
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/component: worker
        app.kubernetes.io/part-of: opssight
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/opssight/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/opssight/secret.yaml") . | sha256sum }}
{{- with .Values.opssight.pod.annotations }}
{{ toYaml . | indent 8 }}
{{- end }}
    spec:
      {{- template "opslevel.pullSecrets" . }}
      {{- template "global.nodeSelector" . }}
      priorityClassName: opslevel-normal
      terminationGracePeriodSeconds: 315
      containers:
        - name: opssight-worker
          image: "{{ template "opssight.image" . }}"
          command:
          - /usr/local/bin/bundle
          - exec
          - sidekiq
          - -C
          - /opt/app/sidekiq.yml
          envFrom:
          - configMapRef:
              name: '{{ .Values.opssight.secret.name }}'
          - secretRef:
              name: '{{ .Values.opssight.secret.name }}'
          {{- with .Values.opssight.worker.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}