{{- if .Values.elasticsearch.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: '{{ .Values.elasticsearch.secret.name }}'
  labels:
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: elasticsearch
type: Opaque
data:
  ELASTIC_PASSWORD: '{{ .Values.elasticsearch.secret.password | b64enc }}'
{{- end }}