{{- if .Values.elasticsearch.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: '{{ .Values.elasticsearch.serviceAccount.name }}'
  labels:
    app.kubernetes.io/component: serviceAccount
    app.kubernetes.io/part-of: elasticsearch
{{- with .Values.elasticsearch.serviceAccount.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}
