{{- if eq .Values.elasticsearch.external false }}
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: elasticsearch
spec:
  publishNotReadyAddresses: true
  clusterIP: None
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
  selector:
    app.kubernetes.io/component: app
    app.kubernetes.io/part-of: elasticsearch
{{- end }}