{{- if .Values.collect.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opslevel-collector
  labels:
    {{- include "opslevel.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    opslevel.com/description: "A tool that sends your Kubernetes resources as payloads to a Custom Event integration."
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "opslevel.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: "collector"
  template:
    metadata:
      labels:
        {{- include "opslevel.labels" . | nindent 8 }}
        app.kubernetes.io/component: "collector"
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ include "opslevel.serviceAccountName" . }}
      initContainers:
        {{- with .Values.additionalInitContainers }}
          {{- toYaml . | nindent 6 }}
        {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image }}
        imagePullPolicy: IfNotPresent
        args:
          - collect
          - -i "{{- .Values.collect.integration }}"
        envFrom:
        {{- if not .Values.apitokenPath }}
        - secretRef:
            name: {{ .Values.apitokenSecret.name }}
            optional: true
        {{- end }}
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        volumeMounts:
        - name: config
          mountPath: /app
        {{- with .Values.additionalVolumeMounts }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ template "opslevel.fullname" . }}
      {{- with .Values.additionalVolumes }}
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 6 }}
      {{- end }}
{{- end }}
