apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "opslevel-sync.fullname" . }}
  labels:
    {{- include "opslevel-sync.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "opslevel-sync.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "opslevel-sync.labels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ include "opslevel-sync.serviceAccountName" . }}
      initContainers:
        {{- with .Values.additionalInitContainers }}
          {{- toYaml . | nindent 6 }}
        {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image }}
        imagePullPolicy: IfNotPresent
        args:
          - service
          - reconcile
          {{- with .Values.sync.args }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- if .Values.apitokenPath }}
          - --api-token-path
          - {{ .Values.apitokenPath }}
          {{- end }}
        envFrom:
        {{- if not .Values.apitokenPath }}
        - secretRef:
            name: {{ .Values.apitokenSecret.name }}
            optional: true
        {{- end }}
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        volumeMounts:
        - name: config
          mountPath: /app
        {{- with .Values.additionalVolumeMounts }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ template "opslevel-sync.fullname" . }}
      {{- with .Values.additionalVolumes }}
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 6 }}
      {{- end }}
