{{- if .Values.postgres.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: '{{ .Values.postgres.secret.name }}'
  labels:
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: postgres
type: Opaque
data:
  POSTGRES_PASSWORD: '{{ .Values.postgres.secret.password | b64enc }}'
  POSTGRES_USER: '{{ .Values.postgres.secret.username | b64enc }}'
  POSTGRES_DB: '{{ .Values.postgres.secret.databaseName | b64enc }}'
{{- end }}