{{- if eq .Values.postgres.external false }}
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: postgres
spec:
  publishNotReadyAddresses: true
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app.kubernetes.io/component: app
    app.kubernetes.io/part-of: postgres
{{- end }}