{{- if .Values.postgres.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: '{{ .Values.postgres.serviceAccount.name }}'
  labels:
    app.kubernetes.io/component: serviceAccount
    app.kubernetes.io/part-of: postgres
{{- end }}
