apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.faktory.secret.name }}
  labels:
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: faktory
type: Opaque
data:
  FAKTORY_LICENSE: '{{ default "" (((.Values.global.replicated).licenseFields).faktory_license).value | b64enc }}'
  FAKTORY_PASSWORD: '{{ .Values.faktory.secret.password | b64enc }}'
