apiVersion: v1
kind: Service
metadata:
  name: faktory
  labels:
    app.kubernetes.io/name: faktory
    app.kubernetes.io/instance: opslevel
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 7419
      name: tcp-server
      targetPort: server
      protocol: TCP
  selector:
    app.kubernetes.io/name: faktory
    app.kubernetes.io/instance: opslevel
