{{- if .Values.mysql.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: '{{ .Values.mysql.secret.name }}'
  labels:
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: mysql
type: Opaque
data:
# These variables don't work because then db schema lood doesn't work
#  MYSQL_DATABASE: '{{ .Values.mysql.secret.databaseName | b64enc }}'
#  MYSQL_USER: '{{ .Values.mysql.secret.username | b64enc }}'
#  MYSQL_PASSWORD: '{{ .Values.mysql.secret.password | b64enc }}'
  MYSQL_ROOT_PASSWORD: '{{ .Values.mysql.secret.password | b64enc }}'
{{- end }}
{{- end }}