{{- if .Values.mysql.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: '{{ .Values.mysql.serviceAccount.name }}'
  labels:
    app.kubernetes.io/component: serviceAccount
    app.kubernetes.io/part-of: mysql
{{- end }}
