{{- if .Values.secret.create -}}
{{- $token := .Values.secret.data.OPSLEVEL_API_TOKEN | required ".Values.secret.data.OPSLEVEL_API_TOKEN is required." -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  {{- with .Values.secret.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: opaque
{{- with .Values.secret.data }}
stringData:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
