{{- if .Values.runner.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opslevel-runner
  labels:
    app.kubernetes.io/component: app
    app.kubernetes.io/part-of: runner
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/component: app
      app.kubernetes.io/part-of: runner
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/component: app
        app.kubernetes.io/part-of: runner
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/runner/secret.yaml") . | sha256sum }}
{{- with .Values.runner.pod.annotations }}
{{ toYaml . | indent 8 }}
{{- end }}
    spec:
      {{- template "opslevel.pullSecrets" . }}
      {{- template "global.nodeSelector" . }}
      priorityClassName: opslevel-normal
      serviceAccountName: {{ .Values.runner.serviceAccount.name }}
      {{- if .Values.certificate.enabled }}
      initContainers:
        - name: init-certs
          image: "{{ template "opslevel.image" . }}"
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - sleep 10; update-ca-certificates; cp -r /etc/ssl/certs/. /data;
          volumeMounts:
            - name: certificate
              mountPath: /usr/local/share/ca-certificates/custom-cert.crt
              subPath: custom-cert.crt
              readOnly: false
            - name: ca
              mountPath: /data
              readOnly: false
      {{- end }}
      containers:
        - name: runner
          image: '{{ template "runner.image" . }}'
          imagePullPolicy: IfNotPresent
          args:
            - run
            - --api-url=http://$(OPSLEVEL_SERVICE_HOST):$(OPSLEVEL_SERVICE_PORT_HTTP)
            - --job-pod-namespace={{ .Release.Namespace }}
            - --job-pod-max-wait=300
            - --job-pod-requests-cpu=300
            - --job-pod-limits-cpu=1000
            - --job-pod-requests-memory=512
            - --job-pod-limits-memory=2048
            - --scaling-enabled
            - --runner-deployment=opslevel-runner
            - --runner-max-replicas={{ .Values.runner.replicas }}
          env:
          - name: RUNNER_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: RUNNER_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          envFrom: &envFrom
            - secretRef:
                name: '{{ .Values.runner.secret.name }}'
          {{- with .Values.runner.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.certificate.enabled }}
          volumeMounts:
            - name: certificate
              mountPath: /usr/local/share/ca-certificates/custom-cert.crt
              subPath: custom-cert.crt
              readOnly: false
            - name: ca
              mountPath: /etc/ssl/certs
          {{- end }}
      {{- if .Values.certificate.enabled }}
      volumes:
        - name: ca
          emptyDir: {}
        - name: certificate
          secret:
            secretName: {{ .Values.certificate.secret.name }}
      {{- end }}
{{- end }}