{{- if .Values.runner.enabled }}
{{- if .Values.runner.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.runner.serviceAccount.name }}
  labels:
    app.kubernetes.io/component: serviceAccount
    app.kubernetes.io/part-of: runner
{{- with .Values.runner.serviceAccount.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: opslevel-runner
  labels:
    app.kubernetes.io/component: role
    app.kubernetes.io/part-of: runner
rules:
- apiGroups:
  - ""
  - "policy"
  resources:
  - "poddisruptionbudgets"
  verbs:
  - create
  - update
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ""
  - "v1"
  resources:
  - "configmaps"
  verbs:
  - create
  - update
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ""
  - "*"
  resources:
  - "pods"
  - "pods/exec"
  - "pods/log"
  verbs:
  - create
  - update
  - delete
  - get
  - list
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - update
  - delete
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - update
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: opslevel-runner
  labels:
    app.kubernetes.io/component: roleBinding
    app.kubernetes.io/part-of: runner
subjects:
- kind: ServiceAccount
  name: opslevel-runner
  namespace: '{{ .Release.Namespace }}'
roleRef:
  kind: Role
  name: opslevel-runner
  apiGroup: rbac.authorization.k8s.io
{{- end }}