{{- if .Values.runner.enabled }}
{{- if .Values.runner.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: '{{ .Values.runner.secret.name }}'
  labels:
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: runner
type: Opaque
data:
  OPSLEVEL_API_TOKEN: '{{ required "Please set the runner API token" .Values.runner.secret.token | b64enc}}'
{{- end }}
{{- end }}