{{- if eq .Values.objectStorage.type "minio" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: minio
  labels:
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: minio
data:
  make-bucket.sh: |
    #! /usr/bin/env bash
    trap "echo [opslevel] Terminated TERM; exit" SIGTERM
    while true; do
      mc --config-dir /opslevel_config config host add opslevel http://minio.{{ .Release.Namespace }}.svc.cluster.local:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD}
      mc --config-dir /opslevel_config ready opslevel
      mc --config-dir /opslevel_config mb --ignore-existing opslevel/${MINIO_BUCKET_NAME}
      mc --config-dir /opslevel_config anonymous set public opslevel/${MINIO_BUCKET_NAME}
      sleep 600 &
      wait $!
    done;
{{- end }}