{{- if eq .Values.objectStorage.type "minio" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: minio
  labels:
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: minio
data:
  make-bucket.sh: |
    #! /usr/bin/env bash
    trap "echo [opslevel] Terminated TERM; exit" SIGTERM
    while true; do
      mc config host add opslevel http://minio.{{ .Release.Namespace }}.svc.cluster.local:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD}
      mc ready opslevel
      mc mb --ignore-existing opslevel/${MINIO_BUCKET_NAME}
      mc anonymous set public opslevel/${MINIO_BUCKET_NAME}
      sleep 600 &
      wait $!
    done;
{{- end }}