{{- if eq .Values.objectStorage.type "minio" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-create-bucket
  labels:
    app.kubernetes.io/component: create-bucket
    app.kubernetes.io/part-of: minio
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/component: create-bucket
      app.kubernetes.io/part-of: minio
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/component: create-bucket
        app.kubernetes.io/part-of: minio
    spec:
      containers:
      - name: minio-mc
        image: '{{ template "objectStorageCLI.image" . }}'
        imagePullPolicy: IfNotPresent
        command: 
          - "/opslevel/make-bucket.sh"
        envFrom:
        - secretRef:
            name: minio
        volumeMounts:
          - name: scripts
            mountPath: /opslevel
          - name: config
            mountPath: /opslevel_config
      volumes:
        - name: scripts
          configMap:
            name: minio
            defaultMode: 0777
        - name: config
          emptyDir: {}
{{- end }}