{{- if eq .Values.objectStorage.type "minio" }}
{{- if .Values.objectStorage.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: minio
  labels:
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: minio
type: Opaque
data:
  MINIO_ROOT_USER: '{{ .Values.objectStorage.secret.accessKey | b64enc }}'
  MINIO_ROOT_PASSWORD: '{{ .Values.objectStorage.secret.secretKey | b64enc }}'
  MINIO_BUCKET_NAME: '{{ .Values.objectStorage.secret.bucketName | b64enc }}'
{{- end }}
{{- end }}