{{- if eq .Values.objectStorage.type "minio" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: minio
  labels:
    app.kubernetes.io/component: serviceAccount
    app.kubernetes.io/part-of: minio
{{- end }}