{{- if eq .Values.objectStorage.type "minio" }}
apiVersion: v1
kind: Service
metadata:
  name: minio
  labels:
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: minio
spec:
  publishNotReadyAddresses: true
  clusterIP: None
  ports:
    - name: http
      port: 9000
      protocol: TCP
  selector:
    app.kubernetes.io/component: app
    app.kubernetes.io/part-of: minio
---
apiVersion: v1
kind: Service
metadata:
  name: minio-console
  labels:
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: minio
spec:
  ports:
    - name: http-console
      port: 9001
      protocol: TCP
      targetPort: 9001
  selector:
    app.kubernetes.io/component: app
    app.kubernetes.io/part-of: minio
{{- end }}