{{- if eq .Values.objectStorage.type "minio" }}
{{- if .Values.objectStorage.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: '{{ .Values.objectStorage.serviceAccount.name }}'
  labels:
    app.kubernetes.io/component: serviceAccount
    app.kubernetes.io/part-of: minio
{{- with .Values.objectStorage.serviceAccount.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}
{{- end }}