apiVersion: v1
kind: Secret
metadata:
  name: {{ template "utils.name" . }}
  labels:
    {{- include "utils.labels" . | nindent 4 }}
type: Opaque
data:
  OUTBOUND_TOKEN: "{{ .Values.real_token | b64enc }}"
  INBOUND_TOKEN: "{{ .Values.dummy_token | b64enc }}"
