apiVersion: v1
kind: Secret
metadata:
  name: '{{ .Values.redis.secret.name }}'
  labels:
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: redis
type: Opaque
data:
  REDIS_SECURE: '{{ .Values.redis.secret.tls | toString | b64enc }}'
  REDIS_HOST: '{{ .Values.redis.secret.host | b64enc }}'
  REDIS_PORT: '{{ .Values.redis.secret.port | b64enc }}'
  REDIS_USERNAME: '{{ .Values.redis.secret.username | b64enc }}'
  REDIS_PASSWORD: '{{ .Values.redis.secret.password | b64enc }}'