{{- if .Values.redis.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: '{{ .Values.redis.serviceAccount.name }}'
  labels:
    app.kubernetes.io/component: serviceAccount
    app.kubernetes.io/part-of: redis
{{- with .Values.redis.serviceAccount.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}